### ISSUE TITLE
I'm getting an error when running app.js about import modules

### ISSUE THREAD

**Issue by EggbertFluffle** [SlysDev/inverted-website-blocker#2]
Uncaught SyntaxError: Cannot use import statement outside a module
Line1:  import siteBlockingManager from "./modules/site-blocking-manager";

**Comment by jeremykamber** [comment]
I've run into that problem as well with other JavaScript projects. Create a package.json file, and add this:

```
// package.json
{
  "type": "module"
}
```

Let me know if that fixes the issue
